"""empty message

Revision ID: 27ff6051ca7a
Revises: 
Create Date: 2017-06-12 21:43:52.877000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ff6051ca7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=40), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'articles', sa.Column('tagId', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'articles', 'tagId')
    op.drop_table('tags')
    ### end Alembic commands ###
