"""empty message

Revision ID: d0417da48687
Revises: 
Create Date: 2017-06-05 22:47:27.374000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0417da48687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_timestamp', table_name='articles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_timestamp', 'articles', ['timestamp'], unique=False)
    ### end Alembic commands ###
